Repository Harmos274/SQA-Assignment, pull requests merged in 2022-03, with the labels that each got.

#7 Add the Project Plan
  project_plan.md
Labels: documentation, enhancement

#13 Add SOLID principles sub section on Coding standards
  README.md
Labels: enhancement

#20 Add keypoints for coding standards section
  README.md
Labels: enhancement

#12 Add an explanation of what is Fibonacci scale and Fibonacci sequence
  task_estimation.md
Labels: enhancement

#21 Add code reviews most common errors
  README.md
Labels: enhancement

#24 Add keypoints for Code review section
  README.md
Labels: enhancement

#23 Add Coding standards section
  README.md
  assets/coding_standards-pyramide.png
Labels: enhancement

#22 Merge task_estimation.md content into README.md
  README.md
  task_estimation.md
Labels: enhancement

#26 Add task estimation part
  README.md
  assets/task_estimation_discuss.png
Labels: enhancement

#27 Add the list of potential changes
  potential_changes.md
Labels: documentation

#28 Push the whole project on main branch
  README.md
  assets/coding_standards-pyramide.png
  assets/task_estimation_discuss.png
  potential_changes.md
  project_plan.md
Labels: enhancement
